_build:
	gcc -g -std=c99 src/include/src/*.c src/main.c -o build/createProject

# Same thing as _build but without the -g flag
_deploy: 
	gcc -std=c99 src/include/src/*.c src/main.c -o build/createProject
